name: Prod FE workflow

on:
  push:
    branches: [ "master" ]
    paths:
      - packages/frontend/**

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./packages/frontend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./packages/frontend/package.json
      - name: Install deps
        run: npm install --no-audit --progress=false
      # - name: Restart FE
      #   run: pm2 restart frontend